import re
regex_countries = [
    re.compile(r"(Taiwan)"),
    re.compile(r"(Afghanistan)"),
    re.compile(r"(Albania)"),
    re.compile(r"(Algeria)"),
    re.compile(r"(American Samoa)"),
    re.compile(r"(Andorra)"),
    re.compile(r"(Angola)"),
    re.compile(r"(Anguilla)"),
    re.compile(r"(Antarctica)"),
    re.compile(r"(Antigua and Barbuda)"),
    re.compile(r"(Argentina)"),
    re.compile(r"(Armenia)"),
    re.compile(r"(Aruba)"),
    re.compile(r"(Australia)"),
    re.compile(r"(Austria)"),
    re.compile(r"(Azerbaijan)"),
    re.compile(r"(Bahamas)"),
    re.compile(r"(Bahrain)"),
    re.compile(r"(Bangladesh)"),
    re.compile(r"(Barbados)"),
    re.compile(r"(Belarus)"),
    re.compile(r"(Belgium)"),
    re.compile(r"(Belize)"),
    re.compile(r"(Benin)"),
    re.compile(r"(Bermuda)"),
    re.compile(r"(Bhutan)"),
    re.compile(r"(Bolivia \(Plurinational State of\))"),
    re.compile(r"(Bonaire, Sint Eustatius and Saba)"),
    re.compile(r"(Bosnia and Herzegovina)"),
    re.compile(r"(Botswana)"),
    re.compile(r"(Bouvet Island)"),
    re.compile(r"(Brazil)"),
    re.compile(r"(British Indian Ocean Territory)"),
    re.compile(r"(British Virgin Islands)"),
    re.compile(r"(Brunei Darussalam)"),
    re.compile(r"(Bulgaria)"),
    re.compile(r"(Burkina Faso)"),
    re.compile(r"(Burundi)"),
    re.compile(r"(Cabo Verde)"),
    re.compile(r"(Cambodia)"),
    re.compile(r"(Cameroon)"),
    re.compile(r"(Canada)"),
    re.compile(r"(Cayman Islands)"),
    re.compile(r"(Central African Republic)"),
    re.compile(r"(Chad)"),
    re.compile(r"(Chile)"),
    re.compile(r"(China)"),
    re.compile(r"(China, Hong Kong Special Administrative Region)"),
    re.compile(r"(China, Macao Special Administrative Region)"),
    re.compile(r"(Christmas Island)"),
    re.compile(r"(Cocos \(Keeling\) Islands)"),
    re.compile(r"(Colombia)"),
    re.compile(r"(Comoros)"),
    re.compile(r"(Congo)"),
    re.compile(r"(Cook Islands)"),
    re.compile(r"(Costa Rica)"),
    re.compile(r"(Croatia)"),
    re.compile(r"(Cuba)"),
    re.compile(r"(Curaçao)"),
    re.compile(r"(Cyprus)"),
    re.compile(r"(Czechia)"),
    re.compile(r"(Côte d'Ivoire)"),
    re.compile(r"(Democratic People's Republic of Korea)"),
    re.compile(r"(Democratic Republic of the Congo)"),
    re.compile(r"(Denmark)"),
    re.compile(r"(Djibouti)"),
    re.compile(r"(Dominica)"),
    re.compile(r"(Dominican Republic)"),
    re.compile(r"(Ecuador)"),
    re.compile(r"(Egypt)"),
    re.compile(r"(El Salvador)"),
    re.compile(r"(Equatorial Guinea)"),
    re.compile(r"(Eritrea)"),
    re.compile(r"(Estonia)"),
    re.compile(r"(Ethiopia)"),
    re.compile(r"(Falkland Islands \(Malvinas\))"),
    re.compile(r"(Faroe Islands)"),
    re.compile(r"(Fiji)"),
    re.compile(r"(Finland)"),
    re.compile(r"(France)"),
    re.compile(r"(French Guiana)"),
    re.compile(r"(French Polynesia)"),
    re.compile(r"(French Southern Territories)"),
    re.compile(r"(Gabon)"),
    re.compile(r"(Gambia)"),
    re.compile(r"(Georgia)"),
    re.compile(r"(Germany)"),
    re.compile(r"(Ghana)"),
    re.compile(r"(Gibraltar)"),
    re.compile(r"(Greece)"),
    re.compile(r"(Greenland)"),
    re.compile(r"(Grenada)"),
    re.compile(r"(Guadeloupe)"),
    re.compile(r"(Guam)"),
    re.compile(r"(Guatemala)"),
    re.compile(r"(Guernsey)"),
    re.compile(r"(Guinea)"),
    re.compile(r"(Guinea-Bissau)"),
    re.compile(r"(Guyana)"),
    re.compile(r"(Haiti)"),
    re.compile(r"(Heard Island and McDonald Islands)"),
    re.compile(r"(Holy See)"),
    re.compile(r"(Honduras)"),
    re.compile(r"(Hungary)"),
    re.compile(r"(Iceland)"),
    re.compile(r"(India)"),
    re.compile(r"(Indonesia)"),
    re.compile(r"(Iran \(Islamic Republic of\))"),
    re.compile(r"(Iraq)"),
    re.compile(r"(Ireland)"),
    re.compile(r"(Isle of Man)"),
    re.compile(r"(Israel)"),
    re.compile(r"(Italy)"),
    re.compile(r"(Jamaica)"),
    re.compile(r"(Japan)"),
    re.compile(r"(Jersey)"),
    re.compile(r"(Jordan)"),
    re.compile(r"(Kazakhstan)"),
    re.compile(r"(Kenya)"),
    re.compile(r"(Kiribati)"),
    re.compile(r"(Kuwait)"),
    re.compile(r"(Kyrgyzstan)"),
    re.compile(r"(Lao People's Democratic Republic)"),
    re.compile(r"(Latvia)"),
    re.compile(r"(Lebanon)"),
    re.compile(r"(Lesotho)"),
    re.compile(r"(Liberia)"),
    re.compile(r"(Libya)"),
    re.compile(r"(Liechtenstein)"),
    re.compile(r"(Lithuania)"),
    re.compile(r"(Luxembourg)"),
    re.compile(r"(Madagascar)"),
    re.compile(r"(Malawi)"),
    re.compile(r"(Malaysia)"),
    re.compile(r"(Maldives)"),
    re.compile(r"(Mali)"),
    re.compile(r"(Malta)"),
    re.compile(r"(Marshall Islands)"),
    re.compile(r"(Martinique)"),
    re.compile(r"(Mauritania)"),
    re.compile(r"(Mauritius)"),
    re.compile(r"(Mayotte)"),
    re.compile(r"(Mexico)"),
    re.compile(r"(Micronesia \(Federated States of\))"),
    re.compile(r"(Monaco)"),
    re.compile(r"(Mongolia)"),
    re.compile(r"(Montenegro)"),
    re.compile(r"(Montserrat)"),
    re.compile(r"(Morocco)"),
    re.compile(r"(Mozambique)"),
    re.compile(r"(Myanmar)"),
    re.compile(r"(Nauru)"),
    re.compile(r"(Nepal)"),
    re.compile(r"(Netherlands)"),
    re.compile(r"(New Caledonia)"),
    re.compile(r"(New Zealand)"),
    re.compile(r"(Nicaragua)"),
    re.compile(r"(Niger)"),
    re.compile(r"(Nigeria)"),
    re.compile(r"(Niue)"),
    re.compile(r"(Norfolk Island)"),
    re.compile(r"(Northern Mariana Islands)"),
    re.compile(r"(Norway)"),
    re.compile(r"(Oman)"),
    re.compile(r"(Pakistan)"),
    re.compile(r"(Palau)"),
    re.compile(r"(Panama)"),
    re.compile(r"(Papua New Guinea)"),
    re.compile(r"(Paraguay)"),
    re.compile(r"(Peru)"),
    re.compile(r"(Philippines)"),
    re.compile(r"(Pitcairn)"),
    re.compile(r"(Poland)"),
    re.compile(r"(Portugal)"),
    re.compile(r"(Puerto Rico)"),
    re.compile(r"(Qatar)"),
    re.compile(r"(Republic of Korea)"),
    re.compile(r"(Republic of Moldova)"),
    re.compile(r"(Romania)"),
    re.compile(r"(Russian Federation)"),
    re.compile(r"(Rwanda)"),
    re.compile(r"(Réunion)"),
    re.compile(r"(Saint Barthélemy)"),
    re.compile(r"(Saint Helena)"),
    re.compile(r"(Saint Kitts and Nevis)"),
    re.compile(r"(Saint Lucia)"),
    re.compile(r"(Saint Martin \(French Part\))"),
    re.compile(r"(Saint Pierre and Miquelon)"),
    re.compile(r"(Saint Vincent and the Grenadines)"),
    re.compile(r"(Samoa)"),
    re.compile(r"(San Marino)"),
    re.compile(r"(Sao Tome and Principe)"),
    re.compile(r"(Saudi Arabia)"),
    re.compile(r"(Senegal)"),
    re.compile(r"(Serbia)"),
    re.compile(r"(Seychelles)"),
    re.compile(r"(Sierra Leone)"),
    re.compile(r"(Singapore)"),
    re.compile(r"(Sint Maarten \(Dutch part\))"),
    re.compile(r"(Slovakia)"),
    re.compile(r"(Slovenia)"),
    re.compile(r"(Solomon Islands)"),
    re.compile(r"(Somalia)"),
    re.compile(r"(South Africa)"),
    re.compile(r"(South Georgia and the South Sandwich Islands)"),
    re.compile(r"(South Sudan)"),
    re.compile(r"(Spain)"),
    re.compile(r"(Sri Lanka)"),
    re.compile(r"(State of Palestine)"),
    re.compile(r"(Sudan)"),
    re.compile(r"(Suriname)"),
    re.compile(r"(Svalbard and Jan Mayen Islands)"),
    re.compile(r"(Swaziland)"),
    re.compile(r"(Sweden)"),
    re.compile(r"(Switzerland)"),
    re.compile(r"(Syrian Arab Republic)"),
    re.compile(r"(Tajikistan)"),
    re.compile(r"(Thailand)"),
    re.compile(r"(The former Yugoslav Republic of Macedonia)"),
    re.compile(r"(Timor-Leste)"),
    re.compile(r"(Togo)"),
    re.compile(r"(Tokelau)"),
    re.compile(r"(Tonga)"),
    re.compile(r"(Trinidad and Tobago)"),
    re.compile(r"(Tunisia)"),
    re.compile(r"(Turkey)"),
    re.compile(r"(Turkmenistan)"),
    re.compile(r"(Turks and Caicos Islands)"),
    re.compile(r"(Tuvalu)"),
    re.compile(r"(Uganda)"),
    re.compile(r"(Ukraine)"),
    re.compile(r"(United Arab Emirates)"),
    re.compile(r"(United Kingdom of Great Britain and Northern Ireland)"),
    re.compile(r"(United Republic of Tanzania)"),
    re.compile(r"(United States Minor Outlying Islands)"),
    re.compile(r"(United States Virgin Islands)"),
    re.compile(r"(United States of America)"),
    re.compile(r"(Uruguay)"),
    re.compile(r"(Uzbekistan)"),
    re.compile(r"(Vanuatu)"),
    re.compile(r"(Venezuela \(Bolivarian Republic of\))"),
    re.compile(r"(Viet Nam)"),
    re.compile(r"(Wallis and Futuna Islands)"),
    re.compile(r"(Western Sahara)"),
    re.compile(r"(Yemen)"),
    re.compile(r"(Zambia)"),
    re.compile(r"(Zimbabwe)"),
    re.compile(r"(Åland Islands)"),
    re.compile(r"(Kosovo)"),
    re.compile(r"(Namibia)"),
    re.compile(r"(Netherlands Antilles)"),
    re.compile(r"(Northern Mali)"),
    re.compile(r'(Syria)'),
    re.compile(r'(Syrian)'),
    re.compile(r'(Crimea)'),
    re.compile(r'(Republic of Moldova)'),
    # Latakia Province, Syria
    # former Yugoslavia
    re.compile(r'(Yugoslavia)'),
    re.compile(r'(Iran)'),
    re.compile(r'(Iranian)'),
    re.compile(r'(Afghanistan)'),
    re.compile(r'(Kazakhstan)'),
    re.compile(r'(Tunisian)'),
    re.compile(r'(USSR)'),
    re.compile(r'(Ethiopian)'),
    re.compile(r'(United States of America)'),
    re.compile(r'(Germany)'),
    re.compile(r'(French)'),
    re.compile(r'(Bahrain)'),
    re.compile(r'(Kuwaiti)'),
    re.compile(r'(Turkish)'),
    re.compile(r'(Belgian)'),
    re.compile(r'(Saudi Arabia)'),
    re.compile(r'(Lebanon)'),
    re.compile(r'(Indonesian)'),
    re.compile(r'(Sudanese)'),
    re.compile(r'(Tunisian)'),
    re.compile(r'(USSR)'),
    re.compile(r'(Ethiopian)'),
    re.compile(r'(United States of America)'),
    re.compile(r'(Germany)'),
    re.compile(r'(Iranian)'),
    re.compile(r'(French)'),
    re.compile(r'(Bahrain)'),
    re.compile(r'(Kuwaiti)'),
    re.compile(r'(Belgian)'),
    re.compile(r'(Indonesian)'),
    re.compile(r'(Sudanese)'),
    re.compile(r'(British)'),
    re.compile(r'(DPRK)'),
    re.compile(r"(Pakistani)"),
    re.compile(r"(Saudi Arabian)"),
    re.compile(r"(Russian national)"),
    re.compile(r"(Chinese)"),
    re.compile(r"(Afghan)"),
    re.compile(r"(Italian)"),
    re.compile(r"(Moroccan)"),

]
bad_name_map = {
    #--- Nationalities
    "DPRK": "Democratic People's Republic of Korea",
    "Libyan Arab Jamahiriya" : "Libya",
    "USSR" : "Russia",
    "Iran" : "Iran (Islamic Republic of)",
    "RSFSR" : "Russia",
    "Sultanate of Oman" : "Oman",
    "Union of the Comoros" : "Comoros",
    "Africa" : "South Africa",
    "Syria" : "Syrian Arab Republic",
    "Syrian" : "Syrian Arab Republic",
    "DRC" : "Congo",
    "RDC" : "Congo",
    "Central District, Pyongyang": "Democratic People's Republic of Korea",
    "Crimea" :"Russia",
    "Palestinian Territories": "Palestine",
    "Moldova": "Republic of Moldova",
    "Yugoslavia": "The former Yugoslav Republic of Macedonia",
    "Ukranian SSR" : "Ukraine",
    "Ukrainian SSR" : "Ukraine",
    "Ukrainian USSR": "Ukraine",
    "Kazakh SSR": "Kazakhstan",
    "Kazakh Soviet Socialist Republic": "Kazakhstan",
    "SSR" : "Uzbekistan", # ?confusion
    "Autonomous SSR" : "Russia", #? confusion
    "Palestinian": "State of Palestine",
    "Afghan": "Afghanistan",
    "Afghani": "Afghanistan",
    "Afgan": "Afghanistan",
    "Egyptian": "Egypt",
    "Jordanian": "Jordan",
    "Moroccan": "Morocco",
    "French": "France",
    "British": "United Kingdom of Great Britain and Northern Ireland",
    "American": "United States of America",
    "Filipino": "Philippines",
    "Indonesian": "Indonesia",
    "Iraqi": "Iraq",
    "Congolese": "Congo",
    "Turkish": "Turkey",
    "Spanish": "Spain",
    "Russian": "Russian Federation",
    "Mauritian": "Mauritius",
    "Iranian": "Iran",
    "Saudi": "Saudi Arabia",
    "Chinese": "China",
    "Uzbek": "Uzbekistan",
    "Malian": "Mali",
    "North Korean": "Democratic People's Republic of Korea",
    "Taiwanese": "Taiwan",
    "Norwegian": "Norway",
    "Senegalese": "Senegal",
    "Lebanese": "Lebanon",
    "Filipino": "Philippines",
    "Swedish": "Sweden",
    "Ethiopian": "Ethiopia",
    "Tunisian": "Tunisia",
    "Qatarian": "Qatar",
    "Burundian": "Burundi",
    "Canadian": "Canada",
    "Belgian": "Belgium",
    "Kuwaiti": "Kuwait",
    "Sudanese": "Sudan",
    "Pakistani":"Pakistan",
    "Saudi Arabian": "Saudi Arabia",
    "Russian national":"Russian Federation",
    "Italian":"Italy"
}
